import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className={'px-8'}>
      <Head>
        <title>Todo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={
          'min-h-screen py-16 flex flex-col justify-center items-center'
        }
      >
        <h1 className={'m-0 leading-tight text-6xl'}>Todo Next App</h1>
      </main>

      <footer
        className={
          'flex flex-1 py-8 border-solid border-t border-t-indigo-50 justify-center items-center'
        }
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={'h-4 ml-2'}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
